# Copies the files shared between the Chrome extension and the phone web app.
#
# extension\src is the single source of truth for db.js, quiz.js, review.js and
# review.css. This script mirrors them into docs\ (what GitHub Pages serves) and
# rewrites index.html's script tags for the web build. Run it after editing any
# of those four files.

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
$src = Join-Path $root 'extension\src'
$out = Join-Path $root 'docs'

if (-not (Test-Path $out)) { New-Item -ItemType Directory $out | Out-Null }

foreach ($f in 'db.js', 'quiz.js', 'review.js', 'review.css') {
    Copy-Item (Join-Path $src $f) (Join-Path $out $f) -Force
    Write-Output "  copied $f"
}

Write-Output ''
Write-Output "docs\ updated. Files unique to the web app (index.html, sync.js,"
Write-Output "config.js, sw.js, manifest.webmanifest) are not touched."

# collect.js = the shared parser + the bookmarklet's on-page UI, concatenated so
# the phone loads one file and reads the dictionary with the same code as the
# extension.
$collect = @(
    (Get-Content (Join-Path $src 'parser.js') -Raw -Encoding UTF8),
    (Get-Content (Join-Path $out 'collect-ui.js') -Raw -Encoding UTF8)
) -join "`n"
$header = "/* GENERATED by tools\build-pwa.ps1 - edit parser.js or collect-ui.js instead. */`n"
Set-Content (Join-Path $out 'collect.js') ($header + $collect) -Encoding UTF8 -NoNewline
Write-Output "  generated collect.js ($([math]::Round(($header+$collect).Length/1KB,1)) KB)"

# Stamp the service worker with a hash of what it caches. Without this the SW
# keeps serving the previous build from its cache and a deploy appears to do
# nothing - the "why aren't my changes showing up" trap.
$hashInput = ''
foreach ($f in (Get-ChildItem $out -File | Where-Object { $_.Extension -in '.js', '.css', '.html', '.png', '.webmanifest' } | Sort-Object Name)) {
    if ($f.Name -eq 'sw.js') { continue }
    $hashInput += (Get-FileHash $f.FullName -Algorithm SHA256).Hash
}
$stream = [System.IO.MemoryStream]::new([System.Text.Encoding]::UTF8.GetBytes($hashInput))
$version = (Get-FileHash -InputStream $stream -Algorithm SHA256).Hash.Substring(0, 8).ToLower()

$swPath = Join-Path $out 'sw.js'
$sw = Get-Content $swPath -Raw -Encoding UTF8
$sw = $sw -replace "const VERSION = '[^']*';", "const VERSION = '$version';"
Set-Content $swPath $sw -Encoding UTF8 -NoNewline
Write-Output "  stamped sw.js VERSION = $version"
